name             "libyaml"
maintainer       "Joshua Mervine"
maintainer_email "joshua@mervine.net"
license          "MIT"
description      "Installs/Configures ruby"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
recipe           "libyaml::source", "Builds ruby source."
version          "0.1.0"
depends          "build-essential"
depends          "yum"
